# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91aace851c6e1947927aa8cccf949e3a865b08add17b9d8420d9198be42cc81eb38b51a612e3b531a786bae51119d285217f64ad0590e60efb05615277b1267f

test:
  secret_key_base: 9d88b3256135f66d3dd07a7f0e7c39659774970ac4d221a58d81cc776967a6b677c185be20a4a28b85d2fac482d1677b142add6c9708f168fa431f6ac3210e0b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
